REVIEW_TEXT_PATH = "/home/ashutosk/DL_SPAM_REVIEW_CLASSIFICATION/amazon_reviews.txt"
FEATURE_LIST = ["REVIEW_TEXT", "VERIFIED_PURCHASE"]     #["REVIEW_TEXT", "REVIEW_TITLE", "RATING", "PRODUCT_CATEGORY", "VERIFIED_PURCHASE"]
MODEL_NAME = "SVM"   #{"LogisticRegression", "SVM"}
MAX_ITER = 10000
FOLDS = 5
NGRAMS = 3                   #{1, 2, 3}